version: 0.2

environment_variables:
  plaintext:
    HUGO_VERSION: "0.82.1"
    
phases:
  install:
    runtime-versions:
      docker: 18
    commands:                       
        # download Hugo binaries
      - cd /tmp
      - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
      - tar -xzf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
      - mv hugo /usr/bin/hugo
      - cd - 
      - rm -rf /tmp/*
  build:
    commands:
      - rm -rf public
      # build website
      - hugo
      # deployment to the s3 bucket
      - aws s3 sync public/ s3://aws-hugo-website-s3-bucket/ --region us-east-2 --delete
  post_build:
    commands:
      - echo Build completed
